In [2]:
!pip install yfinance

     ---------------------------------------- 0.0/948.2 kB ? eta -:--:--
     ---------------------------------------- 0.0/948.2 kB ? eta -:--:--
     ----------- ---------------------------- 262.1/948.2 kB ? eta -:--:--
     --------------------- ---------------- 524.3/948.2 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 948.2/948.2 kB 1.6 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.17.8-py3-none-any.whl size=139014 sha256=c5ba17f12f80f12ba85d143cf309d0fa1b33ff49743864788537ac4b7e6e3626
  Stored in directory: c:\users\owner\appdata\local\pip\cache\wheels\8f\65\34\456800445efeafb05164fe95285c70e81ba1d96bae30f43917
Successf

ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Python312\\Scripts\\pwiz.py'
Consider using the `--user` option or check the permissions.



In [11]:
import yfinance as yf
import pandas as pd
import numpy as np
# Define the stock ticker and the period for which you want the data
ticker = 'AAPL'
period = '1y'

# Download the stock data
stock_data = yf.download(ticker, period=period)

# Create a DataFrame with the specified columns
df = pd.DataFrame(stock_data)
df.tail()

[*********************100%***********************]  1 of 1 completed


Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date                                                                
2025-01-02  243.850006  249.100006  241.820007  248.929993  55740700
2025-01-03  243.360001  244.179993  241.889999  243.360001  40244100
2025-01-06  245.000000  247.330002  243.199997  244.309998  45045600
2025-01-07  242.210007  245.550003  241.350006  242.979996  40797900
2025-01-08  243.339996  243.378998  240.050003  241.970001   8972334

In [8]:
df.columns

MultiIndex([( 'Close', 'AAPL'),
            (  'High', 'AAPL'),
            (   'Low', 'AAPL'),
            (  'Open', 'AAPL'),
            ('Volume', 'AAPL')],
           names=['Price', 'Ticker'])

In [15]:
data =  df.filter([( 'Close', 'AAPL')])
dataset = data.values

training_data_len = int(np.ceil( len(dataset) * .95 ))
testing_data_len = data.shape[0] - training_data_len

In [39]:
dataset

array([[184.65536499],
       [184.2374115 ],
       [185.28230286],
       [184.68521118],
       [185.01359558],
       [182.73477173],
       [181.78939819],
       [187.71040344],
       [190.62611389],
       [192.94474792],
       [194.22845459],
       [193.55177307],
       [193.22340393],
       [191.48193359],
       [190.79528809],
       [187.1232605 ],
       [183.50102234],
       [185.94903564],
       [184.94395447],
       [186.76502991],
       [188.37713623],
       [188.48660278],
       [187.4019165 ],
       [188.16912842],
       [186.4752655 ],
       [184.37286377],
       [183.48606873],
       [183.1971283 ],
       [181.6526947 ],
       [180.90541077],
       [181.66268921],
       [183.70529175],
       [181.86195374],
       [180.5068512 ],
       [181.97155762],
       [180.76593018],
       [180.0983429 ],
       [179.01226807],
       [174.46871948],
       [169.50665283],
       [168.51025391],
       [168.39068604],
       [170.11445618],
       [172

In [18]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(dataset)

scaled_data

array([[0.21402814],
       [0.20961072],
       [0.22065435],
       [0.21434359],
       [0.21781434],
       [0.19372907],
       [0.18373727],
       [0.24631734],
       [0.27713396],
       [0.30163998],
       [0.31520769],
       [0.30805573],
       [0.30458514],
       [0.28617926],
       [0.27892199],
       [0.24011173],
       [0.2018277 ],
       [0.22770116],
       [0.21707829],
       [0.23632553],
       [0.25336415],
       [0.25452112],
       [0.24305689],
       [0.25116568],
       [0.23326296],
       [0.21104234],
       [0.20166966],
       [0.1986158 ],
       [0.18229243],
       [0.17439426],
       [0.18239806],
       [0.20398666],
       [0.18450412],
       [0.17018182],
       [0.18566254],
       [0.17292007],
       [0.16586423],
       [0.15438533],
       [0.10636382],
       [0.05391893],
       [0.04338782],
       [0.04212409],
       [0.0603429 ],
       [0.08161573],
       [0.08667049],
       [0.0645555 ],
       [0.0842485 ],
       [0.080

In [42]:
v = scaled_data[0:60,0]
v.shape

(60,)

In [19]:
# Create the training data set 
# Create the scaled training data set
train_data = scaled_data[0:int(training_data_len), :]
# Split the data into x_train and y_train data sets
x_train = []
y_train = []

for i in range(60, len(train_data)):
    x_train.append(train_data[i-60:i, 0])
    y_train.append(train_data[i, 0])
    if i<= 61:
        print(x_train)
        print(y_train)
        print()
        
# Convert the x_train and y_train to numpy arrays 
x_train, y_train = np.array(x_train), np.array(y_train)

# Reshape the data
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
# x_train.shape

[array([0.21402814, 0.20961072, 0.22065435, 0.21434359, 0.21781434,
       0.19372907, 0.18373727, 0.24631734, 0.27713396, 0.30163998,
       0.31520769, 0.30805573, 0.30458514, 0.28617926, 0.27892199,
       0.24011173, 0.2018277 , 0.22770116, 0.21707829, 0.23632553,
       0.25336415, 0.25452112, 0.24305689, 0.25116568, 0.23326296,
       0.21104234, 0.20166966, 0.1986158 , 0.18229243, 0.17439426,
       0.18239806, 0.20398666, 0.18450412, 0.17018182, 0.18566254,
       0.17292007, 0.16586423, 0.15438533, 0.10636382, 0.05391893,
       0.04338782, 0.04212409, 0.0603429 , 0.08161573, 0.08667049,
       0.0645555 , 0.0842485 , 0.08024652, 0.0918309 , 0.11668414,
       0.14395953, 0.06708264, 0.07666611, 0.06160679, 0.04960133,
       0.08751314, 0.06824123, 0.05297113, 0.04043927, 0.04896931])]
[0.040228652341355975]

[array([0.21402814, 0.20961072, 0.22065435, 0.21434359, 0.21781434,
       0.19372907, 0.18373727, 0.24631734, 0.27713396, 0.30163998,
       0.31520769, 0.30805573, 0.3

In [40]:
x_train.shape

(181, 60, 1)

In [20]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

# Build the LSTM model
model = Sequential()
model.add(LSTM(128, return_sequences=True, input_shape= (x_train.shape[1], 1)))
model.add(LSTM(64, return_sequences=False))
model.add(Dense(25))
model.add(Dense(1))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(x_train, y_train, batch_size=1, epochs=1)

c:\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


181/181 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - loss: 0.0328


In [33]:
new_test_data = scaled_data[-2:]
x_test_data = []
for i in range()

array([[0.82233255],
       [0.8342756 ]])

In [21]:
test_data = scaled_data[training_data_len - 60: , :]
# Create the data sets x_test and y_test
x_test = []
y_test = dataset[training_data_len:, :]
for i in range(60, len(test_data)):
    x_test.append(test_data[i-60:i, 0])
    
# Convert the data to a numpy array
x_test = np.array(x_test)

# Reshape the data
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1 ))

# Get the models predicted price values 
predictions = model.predict(x_test)
predictions = scaler.inverse_transform(predictions)

# Get the root mean squared error (RMSE)
rmse = np.sqrt(np.mean(((predictions - y_test) ** 2)))
rmse

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


11.046974591660382

In [32]:
test_data

array([[0.66442874],
       [0.66727923],
       [0.72228417],
       [0.65059848],
       [0.65661621],
       [0.64489717],
       [0.65682732],
       [0.60287823],
       [0.64595302],
       [0.68575495],
       [0.68047617],
       [0.66474548],
       [0.7043363 ],
       [0.73125802],
       [0.70940381],
       [0.71331015],
       [0.74339911],
       [0.75902433],
       [0.75247876],
       [0.69863515],
       [0.6966294 ],
       [0.70549762],
       [0.72650709],
       [0.72935759],
       [0.6916672 ],
       [0.64743109],
       [0.61575843],
       [0.60625657],
       [0.62145942],
       [0.61375252],
       [0.66400637],
       [0.66115281],
       [0.63229888],
       [0.63229888],
       [0.64170543],
       [0.6744699 ],
       [0.64043718],
       [0.6723561 ],
       [0.67510402],
       [0.68271383],
       [0.67764068],
       [0.69190895],
       [0.72361644],
       [0.74676294],
       [0.74538889],
       [0.77075498],
       [0.79464123],
       [0.826

In [31]:
y_test

array([[254.49000549],
       [255.27000427],
       [258.20001221],
       [259.01998901],
       [255.58999634],
       [252.19999695],
       [250.41999817],
       [243.8500061 ],
       [243.36000061],
       [245.        ],
       [242.21000671],
       [243.33999634]])

In [25]:
valid = data[training_data_len:][( 'Close', 'AAPL')].to_list()
pred_dict = 

In [26]:
df_pred =

[254.49000549316406,
 255.27000427246094,
 258.20001220703125,
 259.0199890136719,
 255.58999633789062,
 252.1999969482422,
 250.4199981689453,
 243.85000610351562,
 243.36000061035156,
 245.0,
 242.2100067138672,
 243.33999633789062]